import type { DiagramPattern, DiagramSpec } from "@/lib/diagram/types";

const aiRaceSpec: DiagramSpec = {
  id: "ai-race",
  title: "IA - Une course mondiale",
  ariaLabel:
    "Schéma de la course mondiale en IA avec couches applications, entraînement et infrastructure",
  mode: "flow",
  pattern: "ecosystem",
  density: "detailed",
  viewBox: [0, 0, 1200, 760],
  titleBar: { text: "IA - Une course mondiale", tone: "navy" },
  sections: [
    { id: "s1", x: 20, y: 108, width: 640, height: 620, tone: "sky", title: "Pile IA" },
    { id: "s2", x: 680, y: 176, width: 500, height: 520, tone: "slate", title: "Écosystème" },
  ],
  nodes: [
    { id: "n1", x: 92, y: 166, width: 220, height: 52, label: "Applications", tone: "sand" },
    { id: "n2", x: 92, y: 256, width: 220, height: 52, label: "AI Deployment", tone: "sand" },
    { id: "n3", x: 92, y: 346, width: 220, height: 52, label: "AI Training", tone: "sand" },
    {
      id: "n4",
      x: 72,
      y: 446,
      width: 370,
      height: 112,
      label: "Data Center",
      subtitle: "GPU • GPU • GPU",
      tone: "blue",
    },
    {
      id: "n5",
      x: 128,
      y: 596,
      width: 246,
      height: 52,
      label: "Energy ⚡",
      tone: "mint",
      shape: "pill",
    },
    {
      id: "n6",
      x: 712,
      y: 238,
      width: 438,
      height: 70,
      label: "Acteurs: OpenAI, Anthropic, GAFAM,\nAlibaba, Baidu, Oracle, IBM",
      tone: "sand",
      textAlign: "left",
    },
    {
      id: "n7",
      x: 712,
      y: 334,
      width: 438,
      height: 70,
      label: "Puces: Nvidia et accélérateurs\nla bataille se joue sur le hardware",
      tone: "amber",
      textAlign: "left",
    },
    {
      id: "n8",
      x: 712,
      y: 430,
      width: 438,
      height: 70,
      label: "Datacenters: montée en capacité\nmulti-régions et énergie dédiée",
      tone: "blue",
      textAlign: "left",
    },
    {
      id: "n9",
      x: 712,
      y: 526,
      width: 438,
      height: 70,
      label: "Partenariats énergétiques:\nréseaux, nucléaire, infra long terme",
      tone: "mint",
      textAlign: "left",
    },
  ],
  links: [
    { id: "l1", from: [202, 250], to: [202, 222] },
    { id: "l2", from: [202, 340], to: [202, 312] },
    { id: "l3", from: [202, 438], to: [202, 402] },
    { id: "l4", from: [250, 596], to: [250, 560] },
    { id: "l5", from: [360, 192], to: [540, 212], label: "Nous", curve: 12 },
  ],
  annotations: [
    {
      id: "a1",
      x: 36,
      y: 124,
      text: "Applications visibles = partie émergée.\nLe moteur réel est infra + énergie + capacité calcul.",
      tone: "slate",
      size: 14,
    },
  ],
  legends: [
    {
      id: "g1",
      x: 712,
      y: 618,
      width: 438,
      title: "Lecture",
      items: [
        { id: "i1", label: "Bleu: software & orchestration", tone: "blue" },
        { id: "i2", label: "Ambre: compute (GPU / puces)", tone: "amber" },
        { id: "i3", label: "Menthe: énergie & infra", tone: "mint" },
      ],
    },
  ],
};

const definitionsSpec: DiagramSpec = {
  id: "ai-definitions",
  title: "Définitions et champs d'applications",
  ariaLabel: "Diagramme en couches IA, ML, DL et GenAI",
  mode: "layer",
  pattern: "comparison",
  density: "detailed",
  viewBox: [0, 0, 1200, 760],
  titleBar: { text: "Définitions & champs applications", tone: "navy" },
  sections: [{ id: "s1", x: 20, y: 108, width: 560, height: 620, tone: "slate" }],
  nodes: [
    {
      id: "c1",
      x: 70,
      y: 170,
      width: 460,
      height: 460,
      label: "IA",
      shape: "circle",
      tone: "navy",
    },
    {
      id: "c2",
      x: 132,
      y: 232,
      width: 336,
      height: 336,
      label: "ML",
      shape: "circle",
      tone: "blue",
    },
    {
      id: "c3",
      x: 188,
      y: 288,
      width: 224,
      height: 224,
      label: "DL",
      shape: "circle",
      tone: "sky",
    },
    {
      id: "c4",
      x: 220,
      y: 414,
      width: 160,
      height: 160,
      label: "GEN AI",
      shape: "circle",
      tone: "amber",
    },
    { id: "b1", x: 208, y: 590, width: 188, height: 46, label: "AGENTIC AI", tone: "amber" },
    { id: "b2", x: 208, y: 644, width: 188, height: 40, label: "AGI", tone: "rose" },
    {
      id: "n1",
      x: 628,
      y: 170,
      width: 542,
      height: 194,
      label:
        "Classique\nObjectif: résoudre un problème spécifique\nDonnées: structurées\nSortie: classification, score, prévision",
      tone: "sand",
      textAlign: "left",
    },
    {
      id: "n2",
      x: 628,
      y: 394,
      width: 542,
      height: 194,
      label:
        "Nouvelle ère\nObjectif: comprendre et générer\nDonnées: textes bruts, documents, interactions\nSortie: conversation, synthèse, création",
      tone: "blue",
      textAlign: "left",
    },
  ],
  links: [],
  annotations: [
    { id: "a1", x: 24, y: 138, text: "Du plus large (IA) au plus spécifique (GenAI)." },
    {
      id: "a2",
      x: 628,
      y: 618,
      text: "Agentic AI: planifier + agir avec des outils.",
      tone: "slate",
    },
  ],
};

const grandConceptSpec: DiagramSpec = {
  id: "ai-grand-concept",
  title: "AI - Grand concept",
  ariaLabel:
    "Comparaison IA classique et LLM autour du pipeline données entraînement modèle prédiction",
  mode: "flow",
  pattern: "comparison",
  density: "detailed",
  viewBox: [0, 0, 1200, 760],
  titleBar: { text: "AI - Grand concept", tone: "navy" },
  sections: [
    {
      id: "s1",
      x: 20,
      y: 176,
      width: 560,
      height: 540,
      tone: "slate",
      title: "Cas d'une IA classique",
    },
    { id: "s2", x: 620, y: 176, width: 560, height: 540, tone: "slate", title: "Cas d'un LLM" },
  ],
  nodes: [
    { id: "p1", x: 26, y: 108, width: 140, height: 44, label: "Données", tone: "mint" },
    { id: "p2", x: 196, y: 108, width: 188, height: 44, label: "Entraînement", tone: "mint" },
    { id: "p3", x: 418, y: 108, width: 130, height: 44, label: "Modèle", tone: "blue" },
    { id: "p4", x: 586, y: 108, width: 192, height: 44, label: "Prédictions", tone: "blue" },
    {
      id: "c1",
      x: 50,
      y: 250,
      width: 500,
      height: 204,
      label:
        "Exemple Netflix\n• Données: habitudes de visionnage\n• Pattern: corrélations entre contenus\n• Application: recommandations",
      tone: "sand",
      textAlign: "left",
    },
    {
      id: "c2",
      x: 652,
      y: 250,
      width: 500,
      height: 204,
      label:
        "Exemple ChatGPT\n• Données: milliards de phrases\n• Pattern: séquences de mots probables\n• Application: suite de texte cohérente",
      tone: "sand",
      textAlign: "left",
    },
    {
      id: "c3",
      x: 50,
      y: 488,
      width: 500,
      height: 176,
      label: "Point clé: l'IA classique optimise\nune tâche prédéfinie.",
      tone: "amber",
      textAlign: "left",
    },
    {
      id: "c4",
      x: 652,
      y: 488,
      width: 500,
      height: 176,
      label: "Point clé: le LLM ne comprend pas,\nil calcule la meilleure suite statistique.",
      tone: "amber",
      textAlign: "left",
    },
  ],
  links: [
    { id: "l1", from: [166, 130], to: [196, 130] },
    { id: "l2", from: [384, 130], to: [418, 130] },
    { id: "l3", from: [548, 130], to: [586, 130] },
  ],
  annotations: [],
};

const chainInteractionsSpec: DiagramSpec = {
  id: "genai-chain",
  title: "GEN AI - Une chaîne d'interactions",
  ariaLabel: "Comparaison chat classique et chat augmenté avec outils",
  mode: "flow",
  pattern: "augmented-chat",
  density: "detailed",
  viewBox: [0, 0, 1200, 760],
  titleBar: { text: "GEN AI - Une chaîne d'interactions", tone: "navy" },
  sections: [
    {
      id: "s1",
      x: 62,
      y: 180,
      width: 468,
      height: 532,
      dashed: true,
      tone: "slate",
      title: "Chat classique",
    },
    {
      id: "s2",
      x: 676,
      y: 180,
      width: 468,
      height: 532,
      dashed: true,
      tone: "slate",
      title: "Chat augmenté - Outils",
    },
  ],
  nodes: [
    {
      id: "n1",
      x: 96,
      y: 244,
      width: 290,
      height: 46,
      label: "Instructions générales",
      tone: "blue",
    },
    { id: "n2", x: 168, y: 312, width: 146, height: 46, label: "Message", tone: "blue" },
    { id: "n3", x: 168, y: 392, width: 146, height: 46, label: "Réponse", tone: "amber" },
    { id: "n4", x: 168, y: 490, width: 146, height: 46, label: "Message", tone: "blue" },
    { id: "n5", x: 168, y: 566, width: 146, height: 46, label: "Réponse", tone: "amber" },
    {
      id: "n6",
      x: 708,
      y: 244,
      width: 290,
      height: 46,
      label: "Instructions générales",
      tone: "blue",
    },
    { id: "n7", x: 780, y: 302, width: 146, height: 46, label: "Message", tone: "blue" },
    {
      id: "n8",
      x: 726,
      y: 370,
      width: 254,
      height: 78,
      label: "Raisonnement interne\nreformulation / analyse",
      tone: "sand",
    },
    { id: "n9", x: 780, y: 470, width: 146, height: 46, label: "Réponse", tone: "amber" },
    {
      id: "n10",
      x: 732,
      y: 546,
      width: 242,
      height: 66,
      label: "Mémoire + contenus\nréutilisation des étapes",
      tone: "blue",
    },
  ],
  links: [
    { id: "l1", from: [242, 292], to: [242, 312] },
    { id: "l2", from: [242, 358], to: [242, 392] },
    { id: "l3", from: [242, 438], to: [242, 490] },
    { id: "l4", from: [242, 536], to: [242, 566] },
    { id: "l5", from: [854, 292], to: [854, 302] },
    { id: "l6", from: [854, 348], to: [854, 370] },
    { id: "l7", from: [854, 448], to: [854, 470] },
    { id: "l8", from: [854, 516], to: [854, 546] },
  ],
  annotations: [
    {
      id: "a1",
      x: 82,
      y: 140,
      text: "Une IA générative génère la meilleure réponse\navec les informations disponibles.",
      tone: "slate",
    },
    { id: "a2", x: 554, y: 322, text: "Contexte initial", tone: "slate", size: 16 },
    { id: "a3", x: 554, y: 430, text: "Étapes internes", tone: "slate", size: 16 },
    { id: "a4", x: 554, y: 584, text: "Boucle de réutilisation", tone: "slate", size: 16 },
  ],
};

const addToolsSpec: DiagramSpec = {
  id: "genai-tools",
  title: "GEN AI - Ajouter des outils",
  ariaLabel: "Chaîne de recherche internet avec appel outil et réponse augmentée",
  mode: "flow",
  pattern: "augmented-chat",
  density: "detailed",
  viewBox: [0, 0, 1200, 760],
  titleBar: { text: "GEN AI - Ajouter des outils", tone: "navy" },
  sections: [
    {
      id: "s1",
      x: 250,
      y: 130,
      width: 420,
      height: 596,
      dashed: true,
      tone: "slate",
      title: "Recherche internet",
    },
  ],
  nodes: [
    {
      id: "m1",
      x: 286,
      y: 192,
      width: 250,
      height: 72,
      label: "Bonjour, je peux vous aider ?",
      tone: "amber",
      primitive: "message",
    },
    {
      id: "m2",
      x: 352,
      y: 286,
      width: 252,
      height: 72,
      label: "Les dernières nouvelles\nsur le sujet XXX",
      tone: "blue",
      primitive: "message",
    },
    {
      id: "m3",
      x: 292,
      y: 390,
      width: 338,
      height: 166,
      label:
        "1. Demande de recherche\n2. Utiliser outil 'search'\n3. Compiler les résultats\n4. Formuler la réponse",
      tone: "sand",
      textAlign: "left",
    },
    {
      id: "m4",
      x: 296,
      y: 582,
      width: 330,
      height: 76,
      label: "Les dernières news sur\nle sujet XXX sont ...",
      tone: "amber",
      primitive: "message",
    },
    {
      id: "tool",
      x: 32,
      y: 394,
      width: 176,
      height: 70,
      label: "Outil recherche\ninternet",
      tone: "mint",
      shape: "pill",
    },
  ],
  links: [
    { id: "l1", from: [208, 430], to: [292, 430] },
    { id: "l2", from: [208, 450], to: [292, 468] },
  ],
  annotations: [
    {
      id: "a1",
      x: 706,
      y: 442,
      text: "Résultat 'augmenté': la réponse inclut\ndes éléments non présents initialement\ndans le modèle.",
      size: 24,
      tone: "slate",
    },
  ],
};

const knowledgeBaseSpec: DiagramSpec = {
  id: "knowledge-base",
  title: "Base documentaire",
  ariaLabel: "Exemple de base documentaire RH connectée à un assistant",
  mode: "flow",
  pattern: "augmented-chat",
  density: "detailed",
  viewBox: [0, 0, 1200, 760],
  titleBar: { text: "Base documentaire", tone: "navy" },
  sections: [{ id: "s1", x: 410, y: 106, width: 760, height: 636, dashed: true, tone: "slate" }],
  nodes: [
    {
      id: "d1",
      x: 38,
      y: 200,
      width: 318,
      height: 170,
      tone: "rose",
      label: "Documents RH\nOnboarding\nLiens utiles\nProcédures",
    },
    {
      id: "m1",
      x: 500,
      y: 146,
      width: 322,
      height: 78,
      tone: "amber",
      label: "Bonjour, je peux vous aider ?",
      primitive: "message",
    },
    {
      id: "m2",
      x: 660,
      y: 270,
      width: 410,
      height: 96,
      tone: "blue",
      label: "Je suis le nouveau directeur\nde la résidence XXX,\npar où je commence ?",
      primitive: "message",
    },
    {
      id: "m3",
      x: 470,
      y: 406,
      width: 556,
      height: 190,
      tone: "sand",
      label: "Demande d'information\n→ Consultation base RH\n→ Extraction des procédures utiles",
      textAlign: "left",
    },
    {
      id: "m4",
      x: 470,
      y: 620,
      width: 456,
      height: 110,
      tone: "amber",
      label:
        "Bienvenue chez Magora:\n1) étapes de prise de poste\n2) ressources SharePoint\n3) contacts support RH",
      primitive: "message",
      textAlign: "left",
    },
  ],
  links: [
    { id: "l1", from: [356, 280], to: [470, 458] },
    { id: "l2", from: [356, 324], to: [470, 498] },
  ],
  annotations: [],
};

const customToolsSpec: DiagramSpec = {
  id: "custom-tools",
  title: "Outils personnalisés",
  ariaLabel: "Assistant connecté à un outil externe IRESA piloté par un agent",
  mode: "flow",
  pattern: "augmented-chat",
  density: "detailed",
  viewBox: [0, 0, 1200, 760],
  titleBar: { text: "Outils personnalisés", tone: "navy" },
  sections: [
    { id: "s1", x: 30, y: 194, width: 354, height: 302, tone: "sand", title: "Agent - IRESA" },
    {
      id: "s2",
      x: 520,
      y: 116,
      width: 640,
      height: 626,
      dashed: true,
      tone: "slate",
      title: "Assistant - chat",
    },
  ],
  nodes: [
    { id: "n1", x: 90, y: 130, width: 230, height: 52, tone: "rose", label: "IRESA" },
    {
      id: "n2",
      x: 52,
      y: 262,
      width: 310,
      height: 88,
      tone: "slate",
      label: "Transformer la demande\ntexte en requête exploitable",
    },
    {
      id: "n3",
      x: 52,
      y: 374,
      width: 310,
      height: 88,
      tone: "slate",
      label: "Si erreur, relancer en autonomie",
    },
    {
      id: "n4",
      x: 574,
      y: 154,
      width: 300,
      height: 78,
      tone: "amber",
      label: "Bonjour, je peux vous aider ?",
      primitive: "message",
    },
    {
      id: "n5",
      x: 760,
      y: 250,
      width: 334,
      height: 104,
      tone: "blue",
      label: "Combien de dossiers booking\n> 1000€ sur les 6 derniers mois ?",
      primitive: "message",
    },
    {
      id: "n6",
      x: 556,
      y: 380,
      width: 540,
      height: 188,
      tone: "sand",
      label: "Décider d'utiliser l'outil IRESA\nAnalyse de la table\nFormulation de la réponse",
      textAlign: "left",
    },
    {
      id: "n7",
      x: 560,
      y: 600,
      width: 360,
      height: 96,
      tone: "amber",
      label: "Il existe X dossiers > 1000€\nexemple: XXX\\XXXX\\XXX",
      primitive: "message",
      textAlign: "left",
    },
  ],
  links: [
    { id: "l1", from: [206, 182], to: [206, 244], label: "requête" },
    { id: "l2", from: [232, 182], to: [232, 244], label: "résultat" },
    { id: "l3", from: [362, 336], to: [556, 458], label: "extraction IRESA" },
    { id: "l4", from: [362, 312], to: [556, 422], label: "question textuelle" },
  ],
  annotations: [
    {
      id: "a1",
      x: 1040,
      y: 440,
      text: "Les outils peuvent être externes\net eux-mêmes pilotés par IA.",
      tone: "slate",
      size: 18,
    },
  ],
};

const pipelineCompact: DiagramSpec = {
  id: "pattern-pipeline-compact",
  title: "Pattern pipeline compact",
  ariaLabel: "Pipeline données, entraînement, modèle et prédictions en format compact",
  mode: "flow",
  pattern: "pipeline",
  density: "compact",
  viewBox: [0, 0, 1200, 430],
  titleBar: { text: "Pattern Pipeline · compact", tone: "navy" },
  sections: [],
  nodes: [
    { id: "n1", x: 62, y: 190, width: 210, height: 60, tone: "mint", label: "Données" },
    { id: "n2", x: 330, y: 190, width: 240, height: 60, tone: "mint", label: "Entraînement" },
    { id: "n3", x: 628, y: 190, width: 210, height: 60, tone: "blue", label: "Modèle" },
    { id: "n4", x: 896, y: 190, width: 240, height: 60, tone: "blue", label: "Prédictions" },
  ],
  links: [
    { id: "l1", from: [272, 220], to: [330, 220] },
    { id: "l2", from: [570, 220], to: [628, 220] },
    { id: "l3", from: [838, 220], to: [896, 220] },
  ],
  annotations: [],
};

const pipelineDetailed: DiagramSpec = {
  ...pipelineCompact,
  id: "pattern-pipeline-detailed",
  title: "Pattern pipeline détaillé",
  density: "detailed",
  titleBar: { text: "Pattern Pipeline · détaillé", tone: "navy" },
  viewBox: [0, 0, 1200, 560],
  sections: [{ id: "s1", x: 30, y: 156, width: 1140, height: 370, tone: "slate" }],
  annotations: [
    { id: "a1", x: 64, y: 294, text: "Sources internes / externes", tone: "slate" },
    { id: "a2", x: 334, y: 294, text: "Nettoyage, labellisation, fine-tuning", tone: "slate" },
    { id: "a3", x: 630, y: 294, text: "Versioning modèle + évaluation", tone: "slate" },
    { id: "a4", x: 898, y: 294, text: "Classement, génération, aide décision", tone: "slate" },
  ],
};

const pipelineMobile: DiagramSpec = {
  ...pipelineCompact,
  id: "pattern-pipeline-mobile",
  title: "Pattern pipeline mobile",
  density: "mobile",
  titleBar: { text: "Pattern Pipeline · mobile", tone: "navy" },
  viewBox: [0, 0, 760, 860],
  nodes: [
    { id: "n1", x: 150, y: 170, width: 460, height: 70, tone: "mint", label: "Données" },
    { id: "n2", x: 150, y: 300, width: 460, height: 70, tone: "mint", label: "Entraînement" },
    { id: "n3", x: 150, y: 430, width: 460, height: 70, tone: "blue", label: "Modèle" },
    { id: "n4", x: 150, y: 560, width: 460, height: 70, tone: "blue", label: "Prédictions" },
  ],
  links: [
    { id: "l1", from: [380, 240], to: [380, 300] },
    { id: "l2", from: [380, 370], to: [380, 430] },
    { id: "l3", from: [380, 500], to: [380, 560] },
  ],
};

const comparisonCompact: DiagramSpec = {
  id: "pattern-comparison-compact",
  title: "Pattern comparaison compact",
  ariaLabel: "Comparaison à deux colonnes en format compact",
  mode: "layer",
  pattern: "comparison",
  density: "compact",
  viewBox: [0, 0, 1200, 500],
  titleBar: { text: "Pattern Comparaison · compact", tone: "navy" },
  sections: [
    { id: "s1", x: 30, y: 130, width: 540, height: 340, tone: "slate", title: "Classique" },
    { id: "s2", x: 630, y: 130, width: 540, height: 340, tone: "slate", title: "LLM" },
  ],
  nodes: [
    {
      id: "n1",
      x: 66,
      y: 198,
      width: 466,
      height: 96,
      tone: "sand",
      label: "Objectif ciblé\nDonnées structurées",
      textAlign: "left",
    },
    {
      id: "n2",
      x: 66,
      y: 314,
      width: 466,
      height: 96,
      tone: "amber",
      label: "Sortie: score / classe",
      textAlign: "left",
    },
    {
      id: "n3",
      x: 666,
      y: 198,
      width: 466,
      height: 96,
      tone: "sand",
      label: "Objectif génératif\nDonnées textuelles massives",
      textAlign: "left",
    },
    {
      id: "n4",
      x: 666,
      y: 314,
      width: 466,
      height: 96,
      tone: "amber",
      label: "Sortie: texte / conversation",
      textAlign: "left",
    },
  ],
  links: [],
  annotations: [],
};

const comparisonDetailed: DiagramSpec = {
  ...comparisonCompact,
  id: "pattern-comparison-detailed",
  title: "Pattern comparaison détaillé",
  density: "detailed",
  titleBar: { text: "Pattern Comparaison · détaillé", tone: "navy" },
  viewBox: [0, 0, 1200, 620],
  nodes: [
    {
      id: "n1",
      x: 66,
      y: 198,
      width: 466,
      height: 130,
      tone: "sand",
      label: "Classique:\nObjectif spécifique\nDonnées structurées\nRéponse mesurable",
      textAlign: "left",
    },
    {
      id: "n2",
      x: 66,
      y: 346,
      width: 466,
      height: 130,
      tone: "amber",
      label: "Exemple:\nRecommandation Netflix\nDétection de fraude",
      textAlign: "left",
    },
    {
      id: "n3",
      x: 666,
      y: 198,
      width: 466,
      height: 130,
      tone: "sand",
      label: "LLM:\nObjectif généraliste\nCorpus texte géant\nSortie conversationnelle",
      textAlign: "left",
    },
    {
      id: "n4",
      x: 666,
      y: 346,
      width: 466,
      height: 130,
      tone: "amber",
      label: "Exemple:\nAssistant rédaction\nQ&A documentaire",
      textAlign: "left",
    },
  ],
  annotations: [
    { id: "a1", x: 40, y: 560, text: "Même pipeline de base, comportements de sortie différents." },
  ],
};

const comparisonMobile: DiagramSpec = {
  ...comparisonCompact,
  id: "pattern-comparison-mobile",
  title: "Pattern comparaison mobile",
  density: "mobile",
  titleBar: { text: "Pattern Comparaison · mobile", tone: "navy" },
  viewBox: [0, 0, 760, 980],
  sections: [
    { id: "s1", x: 42, y: 126, width: 676, height: 364, tone: "slate", title: "Classique" },
    { id: "s2", x: 42, y: 534, width: 676, height: 364, tone: "slate", title: "LLM" },
  ],
  nodes: [
    {
      id: "n1",
      x: 84,
      y: 212,
      width: 592,
      height: 112,
      tone: "sand",
      label: "Objectif spécifique\nDonnées structurées",
      textAlign: "left",
    },
    {
      id: "n2",
      x: 84,
      y: 344,
      width: 592,
      height: 112,
      tone: "amber",
      label: "Sortie: score / classe",
      textAlign: "left",
    },
    {
      id: "n3",
      x: 84,
      y: 620,
      width: 592,
      height: 112,
      tone: "sand",
      label: "Objectif génératif\nCorpus textuel massif",
      textAlign: "left",
    },
    {
      id: "n4",
      x: 84,
      y: 752,
      width: 592,
      height: 112,
      tone: "amber",
      label: "Sortie: texte / conversation",
      textAlign: "left",
    },
  ],
};

const chatCompact: DiagramSpec = {
  id: "pattern-chat-compact",
  title: "Pattern chat augmenté compact",
  ariaLabel: "Pattern conversation augmentée avec outil en version compacte",
  mode: "flow",
  pattern: "augmented-chat",
  density: "compact",
  viewBox: [0, 0, 1200, 500],
  titleBar: { text: "Pattern Chat Augmenté · compact", tone: "navy" },
  sections: [{ id: "s1", x: 174, y: 130, width: 850, height: 336, dashed: true, tone: "slate" }],
  nodes: [
    {
      id: "n1",
      x: 220,
      y: 176,
      width: 260,
      height: 62,
      tone: "amber",
      label: "Question utilisateur",
      primitive: "message",
    },
    {
      id: "n2",
      x: 520,
      y: 256,
      width: 280,
      height: 92,
      tone: "sand",
      label: "Raisonnement\n+ appel outil",
    },
    { id: "n3", x: 844, y: 176, width: 146, height: 62, tone: "mint", label: "Outil" },
    {
      id: "n4",
      x: 520,
      y: 372,
      width: 280,
      height: 62,
      tone: "amber",
      label: "Réponse augmentée",
      primitive: "message",
    },
  ],
  links: [
    { id: "l1", from: [480, 206], to: [520, 292] },
    { id: "l2", from: [800, 292], to: [844, 206] },
    { id: "l3", from: [660, 348], to: [660, 372] },
  ],
  annotations: [],
};

const chatDetailed: DiagramSpec = {
  ...chatCompact,
  id: "pattern-chat-detailed",
  title: "Pattern chat augmenté détaillé",
  density: "detailed",
  titleBar: { text: "Pattern Chat Augmenté · détaillé", tone: "navy" },
  viewBox: [0, 0, 1200, 620],
  nodes: [
    {
      id: "n1",
      x: 220,
      y: 176,
      width: 260,
      height: 72,
      tone: "amber",
      label: "Question utilisateur",
      primitive: "message",
    },
    {
      id: "n2",
      x: 500,
      y: 266,
      width: 320,
      height: 154,
      tone: "sand",
      label: "1. reformuler\n2. sélectionner outil\n3. synthétiser résultat\n4. rédiger réponse",
      textAlign: "left",
    },
    { id: "n3", x: 856, y: 176, width: 140, height: 72, tone: "mint", label: "Outil API" },
    {
      id: "n4",
      x: 500,
      y: 450,
      width: 320,
      height: 72,
      tone: "amber",
      label: "Réponse augmentée",
      primitive: "message",
    },
  ],
  links: [
    { id: "l1", from: [480, 212], to: [500, 298] },
    { id: "l2", from: [820, 320], to: [856, 212] },
    { id: "l3", from: [660, 420], to: [660, 450] },
  ],
};

const chatMobile: DiagramSpec = {
  ...chatCompact,
  id: "pattern-chat-mobile",
  title: "Pattern chat augmenté mobile",
  density: "mobile",
  titleBar: { text: "Pattern Chat Augmenté · mobile", tone: "navy" },
  viewBox: [0, 0, 760, 980],
  sections: [{ id: "s1", x: 42, y: 126, width: 676, height: 818, dashed: true, tone: "slate" }],
  nodes: [
    {
      id: "n1",
      x: 132,
      y: 194,
      width: 496,
      height: 78,
      tone: "amber",
      label: "Question utilisateur",
      primitive: "message",
    },
    {
      id: "n2",
      x: 132,
      y: 320,
      width: 496,
      height: 172,
      tone: "sand",
      label: "Raisonnement\n+ appel outil\n+ synthèse",
      textAlign: "left",
    },
    { id: "n3", x: 132, y: 544, width: 496, height: 78, tone: "mint", label: "Outil / base / API" },
    {
      id: "n4",
      x: 132,
      y: 676,
      width: 496,
      height: 78,
      tone: "amber",
      label: "Réponse augmentée",
      primitive: "message",
    },
  ],
  links: [
    { id: "l1", from: [380, 272], to: [380, 320] },
    { id: "l2", from: [380, 492], to: [380, 544] },
    { id: "l3", from: [380, 622], to: [380, 676] },
  ],
};

const ecosystemCompact: DiagramSpec = {
  id: "pattern-ecosystem-compact",
  title: "Pattern écosystème compact",
  ariaLabel: "Pattern écosystème IA compact avec couches software, hardware et énergie",
  mode: "layer",
  pattern: "ecosystem",
  density: "compact",
  viewBox: [0, 0, 1200, 520],
  titleBar: { text: "Pattern Écosystème · compact", tone: "navy" },
  sections: [
    { id: "s1", x: 36, y: 140, width: 540, height: 344, tone: "sky", title: "Pile IA" },
    { id: "s2", x: 620, y: 140, width: 540, height: 344, tone: "slate", title: "Acteurs clés" },
  ],
  nodes: [
    { id: "n1", x: 90, y: 206, width: 220, height: 46, tone: "sand", label: "Applications" },
    { id: "n2", x: 90, y: 266, width: 220, height: 46, tone: "sand", label: "Training" },
    { id: "n3", x: 90, y: 328, width: 320, height: 64, tone: "blue", label: "Data center + GPU" },
    { id: "n4", x: 90, y: 406, width: 220, height: 46, tone: "mint", label: "Énergie" },
    {
      id: "n5",
      x: 664,
      y: 214,
      width: 454,
      height: 68,
      tone: "sand",
      label: "Pure players IA + GAFAM + Chine",
      textAlign: "left",
    },
    {
      id: "n6",
      x: 664,
      y: 302,
      width: 454,
      height: 68,
      tone: "amber",
      label: "Compute: Nvidia, ASIC, cloud",
      textAlign: "left",
    },
    {
      id: "n7",
      x: 664,
      y: 390,
      width: 454,
      height: 68,
      tone: "mint",
      label: "Infra énergie et partenariats",
      textAlign: "left",
    },
  ],
  links: [],
  annotations: [],
};

const ecosystemDetailed: DiagramSpec = {
  ...ecosystemCompact,
  id: "pattern-ecosystem-detailed",
  title: "Pattern écosystème détaillé",
  density: "detailed",
  titleBar: { text: "Pattern Écosystème · détaillé", tone: "navy" },
  viewBox: [0, 0, 1200, 620],
  sections: [
    { id: "s1", x: 36, y: 140, width: 540, height: 444, tone: "sky", title: "Pile IA" },
    { id: "s2", x: 620, y: 140, width: 540, height: 444, tone: "slate", title: "Acteurs clés" },
  ],
  nodes: [
    { id: "n1", x: 90, y: 206, width: 220, height: 46, tone: "sand", label: "Applications" },
    { id: "n2", x: 90, y: 266, width: 220, height: 46, tone: "sand", label: "AI deployment" },
    { id: "n3", x: 90, y: 326, width: 220, height: 46, tone: "sand", label: "AI training" },
    {
      id: "n4",
      x: 90,
      y: 388,
      width: 320,
      height: 74,
      tone: "blue",
      label: "Data center\nGPU clusters",
    },
    { id: "n5", x: 90, y: 484, width: 220, height: 46, tone: "mint", label: "Énergie dédiée" },
    {
      id: "n6",
      x: 664,
      y: 214,
      width: 454,
      height: 92,
      tone: "sand",
      label: "OpenAI, Anthropic, Meta,\nGoogle, Alibaba, IBM, Oracle",
      textAlign: "left",
    },
    {
      id: "n7",
      x: 664,
      y: 328,
      width: 454,
      height: 92,
      tone: "amber",
      label: "Nvidia et accélérateurs:\ncapacités, marges, cadence",
      textAlign: "left",
    },
    {
      id: "n8",
      x: 664,
      y: 442,
      width: 454,
      height: 92,
      tone: "mint",
      label: "Datacenters et énergie:\nconstruction + contrats long terme",
      textAlign: "left",
    },
  ],
  links: [
    { id: "l1", from: [200, 252], to: [200, 266] },
    { id: "l2", from: [200, 312], to: [200, 326] },
    { id: "l3", from: [200, 372], to: [200, 388] },
    { id: "l4", from: [200, 462], to: [200, 484] },
  ],
  annotations: [],
};

const ecosystemMobile: DiagramSpec = {
  ...ecosystemCompact,
  id: "pattern-ecosystem-mobile",
  title: "Pattern écosystème mobile",
  density: "mobile",
  titleBar: { text: "Pattern Écosystème · mobile", tone: "navy" },
  viewBox: [0, 0, 760, 1080],
  sections: [
    { id: "s1", x: 36, y: 128, width: 688, height: 430, tone: "sky", title: "Pile IA" },
    { id: "s2", x: 36, y: 588, width: 688, height: 430, tone: "slate", title: "Acteurs clés" },
  ],
  nodes: [
    { id: "n1", x: 108, y: 206, width: 260, height: 48, tone: "sand", label: "Applications" },
    { id: "n2", x: 108, y: 270, width: 260, height: 48, tone: "sand", label: "Training" },
    { id: "n3", x: 108, y: 334, width: 360, height: 64, tone: "blue", label: "Data center + GPU" },
    { id: "n4", x: 108, y: 418, width: 260, height: 48, tone: "mint", label: "Énergie" },
    {
      id: "n5",
      x: 84,
      y: 664,
      width: 592,
      height: 84,
      tone: "sand",
      label: "Pure players IA + GAFAM + Chine",
      textAlign: "left",
    },
    {
      id: "n6",
      x: 84,
      y: 768,
      width: 592,
      height: 84,
      tone: "amber",
      label: "Compute: Nvidia, ASIC, cloud",
      textAlign: "left",
    },
    {
      id: "n7",
      x: 84,
      y: 872,
      width: 592,
      height: 84,
      tone: "mint",
      label: "Infra énergie et partenariats",
      textAlign: "left",
    },
  ],
};

export const diagramSlides: DiagramSpec[] = [
  aiRaceSpec,
  definitionsSpec,
  grandConceptSpec,
  chainInteractionsSpec,
  addToolsSpec,
  knowledgeBaseSpec,
  customToolsSpec,
  pipelineDetailed,
];

export const diagramPatterns: DiagramPattern[] = [
  {
    id: "pipeline",
    label: "Pipeline IA",
    description: "Chaîne canonique Données -> Entraînement -> Modèle -> Prédictions.",
    variants: {
      compact: pipelineCompact,
      detailed: pipelineDetailed,
      mobile: pipelineMobile,
    },
  },
  {
    id: "comparison",
    label: "Comparaison 2 colonnes",
    description: "Mettre en parallèle IA classique et LLM avec les mêmes axes.",
    variants: {
      compact: comparisonCompact,
      detailed: comparisonDetailed,
      mobile: comparisonMobile,
    },
  },
  {
    id: "augmented-chat",
    label: "Chat augmenté",
    description: "Interaction conversationnelle avec raisonnement, outils et restitution.",
    variants: {
      compact: chatCompact,
      detailed: chatDetailed,
      mobile: chatMobile,
    },
  },
  {
    id: "ecosystem",
    label: "Architecture écosystème",
    description: "Lecture par couches: applications, compute et énergie.",
    variants: {
      compact: ecosystemCompact,
      detailed: ecosystemDetailed,
      mobile: ecosystemMobile,
    },
  },
];
